//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTimetable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentTimetable.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AddLessonCheckEntriesAlertAccept {
            get {
                return ResourceManager.GetString("AddLessonCheckEntriesAlertAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entries should not be empty, and the office should be a number!.
        /// </summary>
        internal static string AddLessonCheckEntriesAlertText {
            get {
                return ResourceManager.GetString("AddLessonCheckEntriesAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check entries.
        /// </summary>
        internal static string AddLessonCheckEntriesAlertTitle {
            get {
                return ResourceManager.GetString("AddLessonCheckEntriesAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add lesson.
        /// </summary>
        internal static string AddLessonPageTitle {
            get {
                return ResourceManager.GetString("AddLessonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color progression.
        /// </summary>
        internal static string ColorProgressionLabel {
            get {
                return ResourceManager.GetString("ColorProgressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EditHomeworkCheckEntriesAlertAccept {
            get {
                return ResourceManager.GetString("EditHomeworkCheckEntriesAlertAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entries should not be empty!.
        /// </summary>
        internal static string EditHomeworkCheckEntriesAlertText {
            get {
                return ResourceManager.GetString("EditHomeworkCheckEntriesAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check entries.
        /// </summary>
        internal static string EditHomeworkCheckEntriesAlertTitle {
            get {
                return ResourceManager.GetString("EditHomeworkCheckEntriesAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class type.
        /// </summary>
        internal static string EditLessonPageClassTypeLabel {
            get {
                return ResourceManager.GetString("EditLessonPageClassTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string EditLessonPageCourseLabel {
            get {
                return ResourceManager.GetString("EditLessonPageCourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End at.
        /// </summary>
        internal static string EditLessonPageEndTimeLabel {
            get {
                return ResourceManager.GetString("EditLessonPageEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string EditLessonPageOfficeLabel {
            get {
                return ResourceManager.GetString("EditLessonPageOfficeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        internal static string EditLessonPageStartTimeLabel {
            get {
                return ResourceManager.GetString("EditLessonPageStartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string EditLessonPageTeacherLabel {
            get {
                return ResourceManager.GetString("EditLessonPageTeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit lesson.
        /// </summary>
        internal static string EditLessonPageTitle {
            get {
                return ResourceManager.GetString("EditLessonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the week.
        /// </summary>
        internal static string EditLessonPageWeekDayLabel {
            get {
                return ResourceManager.GetString("EditLessonPageWeekDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End tm.
        /// </summary>
        internal static string EndTimeLabel {
            get {
                return ResourceManager.GetString("EndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ExitAlertNo {
            get {
                return ResourceManager.GetString("ExitAlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave this page? You will lose all entered data!.
        /// </summary>
        internal static string ExitAlertText {
            get {
                return ResourceManager.GetString("ExitAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave?.
        /// </summary>
        internal static string ExitAlertTitle {
            get {
                return ResourceManager.GetString("ExitAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ExitAlertYes {
            get {
                return ResourceManager.GetString("ExitAlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string FridayTextLabel {
            get {
                return ResourceManager.GetString("FridayTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add homework.
        /// </summary>
        internal static string HomeworkAddModalPageTitle {
            get {
                return ResourceManager.GetString("HomeworkAddModalPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name.
        /// </summary>
        internal static string HomeworkControlCourseName {
            get {
                return ResourceManager.GetString("HomeworkControlCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string HomeworkControlDueDate {
            get {
                return ResourceManager.GetString("HomeworkControlDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string HomeworkControlTitle {
            get {
                return ResourceManager.GetString("HomeworkControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string HomeworkEditPageDueDateLabel {
            get {
                return ResourceManager.GetString("HomeworkEditPageDueDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string HomeworkEditPageSubjectPickerLabel {
            get {
                return ResourceManager.GetString("HomeworkEditPageSubjectPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string HomeworkEditPageTextEntry {
            get {
                return ResourceManager.GetString("HomeworkEditPageTextEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit homework.
        /// </summary>
        internal static string HomeworkEdtPageModalTitle {
            get {
                return ResourceManager.GetString("HomeworkEdtPageModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed tasks.
        /// </summary>
        internal static string HomeworkPageCompletedTasks {
            get {
                return ResourceManager.GetString("HomeworkPageCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tasks.
        /// </summary>
        internal static string HomeworkPageCurrentTasks {
            get {
                return ResourceManager.GetString("HomeworkPageCurrentTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string HomeworkPageModalAddButton {
            get {
                return ResourceManager.GetString("HomeworkPageModalAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string HomeworkPageModalDeleteButton {
            get {
                return ResourceManager.GetString("HomeworkPageModalDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homework.
        /// </summary>
        internal static string HomeworkPageTitle {
            get {
                return ResourceManager.GetString("HomeworkPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string IsCompletedLabel {
            get {
                return ResourceManager.GetString("IsCompletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string LessonPageAddButton {
            get {
                return ResourceManager.GetString("LessonPageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LessonPageDeleteButton {
            get {
                return ResourceManager.GetString("LessonPageDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightThemeLabel {
            get {
                return ResourceManager.GetString("LightThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string MondayTextLabel {
            get {
                return ResourceManager.GetString("MondayTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string OfficeLabel {
            get {
                return ResourceManager.GetString("OfficeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll do it later.
        /// </summary>
        internal static string SaveSettingAlertNo {
            get {
                return ResourceManager.GetString("SaveSettingAlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply this setting, you need to restart the application..
        /// </summary>
        internal static string SaveSettingAlertText {
            get {
                return ResourceManager.GetString("SaveSettingAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving setting.
        /// </summary>
        internal static string SaveSettingAlertTitle {
            get {
                return ResourceManager.GetString("SaveSettingAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        internal static string SaveSettingAlertYes {
            get {
                return ResourceManager.GetString("SaveSettingAlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Str tm.
        /// </summary>
        internal static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string SubjectPickerTittle {
            get {
                return ResourceManager.GetString("SubjectPickerTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemThemeLabel {
            get {
                return ResourceManager.GetString("SystemThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string TeacherLabel {
            get {
                return ResourceManager.GetString("TeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string ThursdayTextLabel {
            get {
                return ResourceManager.GetString("ThursdayTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        internal static string TimetablePageTitle {
            get {
                return ResourceManager.GetString("TimetablePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TuesdayTextLabel {
            get {
                return ResourceManager.GetString("TuesdayTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WednesdayTextLabel {
            get {
                return ResourceManager.GetString("WednesdayTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the week.
        /// </summary>
        internal static string WeekDayPickerTitle {
            get {
                return ResourceManager.GetString("WeekDayPickerTitle", resourceCulture);
            }
        }
    }
}
